const audio = {
    SET_AUDIO: 'SET_AUDIO',
    SET_CURRENT_TRACK: 'SET_CURRENT_TRACK',
    CHANGE_CURRENT_TIME: 'CHANGE_CURRENT_TIME',
    PAUSE_TRACK: 'PAUSE_TRACK',
    PLAY_TRACK: 'PLAY_TRACK',

}
export default audio;